[package]
name = "hex-conservative"
version = "0.4.0"
authors = ["Martin Habovštiak <martin.habovstiak@gmail.com>", "Andrew Poelstra <apoelstra@wpsoftware.net>"]
license = "CC0-1.0"
repository = "https://github.com/rust-bitcoin/hex-conservative"
documentation = "https://docs.rs/hex-conservative/"
description = "A hex encoding and decoding crate with a conservative MSRV and dependency policy."
categories = ["encoding"]
keywords = ["encoding", "hex", "hexadecimal"]
readme = "README.md"
edition = "2021"
rust-version = "1.63.0"
exclude = ["tests", "contrib"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace]
members = ["fuzz"]

[features]
default = ["std"]
std = ["alloc", "hex-stable/std"]
alloc = ["hex-stable/alloc"]

[dependencies]
arrayvec = { version = "0.7.2", default-features = false }
hex-stable = { package = "hex-conservative", version = "1.0.0-alpha.0", git = "https://github.com/tcharding/hex-conservative", branch = "02-24-release-1.0-alpha.0", default-features = false }

serde = { version = "1.0", default-features = false, optional = true }


[dev-dependencies]
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0"

[[example]]
name = "hexy"

[[example]]
name = "wrap_array"

[[example]]
name = "serde"
required-features = ["std", "serde"]
